# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.RequirementType'),
            preserve_default=False,
        ),
    ]
